spring.application.name=jwt-auth-backend
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/jwt_auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=YOUR_PASS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=YOUR_SECREAT
app.jwt.expiration-ms=86400000
app.super-admin.email=email@gmail.com
app.super-admin.password=1234567